
name = "my-first-worker"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "NOTIFICATIONS_KV", id = "4595cadd30dd4d20a54bfa3e091b22dc" }
]

[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1